openapi: '3.0.2'
info:
  title: placeholder.app API
  version: '1.0'
servers:
  - url: https://api.placeholder.app
  - url: http://localhost:8080
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
