# name: API Deployment
# author: amattu2
# description: This action handles the API upgrade for the production server

# on:
#   push:
#     branches: ["master"]
#     paths-ignore:
#       - ".vscode/**"
#       - ".github/**"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: ${{ github.repository_owner == 'placeholder-app' }}
#     steps:
#       - name: SSH Into Production
#         run: |
#           ssh ${{ secrets.prod_server }}
#           cd /var/www/backend && git pull origin master
#           make build_linux
#           service API restart
