name: Go Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'placeholder-app' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Compile Application
        run: go build -v ./...
        working-directory: ./

      - name: Run Tests
        run: go test -v ./...
        working-directory: ./
