name: Go Tests

on:
  push:
    branches: ["master"]
    paths-ignore:
      - ".vscode/**"
      - ".github/**"
#    paths:
#      - "**.go"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - ".vscode/**"
      - ".github/**"
#    paths:
#      - "**.go"

jobs:
  tests:
    if: ${{ github.repository_owner == 'placeholder-app' }}  
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Clone repository
      - uses: actions/checkout@v3
        with:
          go-version: ${{ matrix.go-version }}
          
      # Install dependencies
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      # Build application
      - name: Compile Application
        run: go build -v ./...
        working-directory: ./

      # Run tests
      - run: go version
      - run: go test -v ./...
      - run: go test -race ./...
