name: Go Tests

on:
  push:
    branches: ["master"]
    paths-ignore:
      - ".vscode/**"
      - ".github/**"
  pull_request:
    branches: ["master"]
    paths-ignore:
      - ".vscode/**"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'placeholder-app' }}
    steps:
      # Clone repository
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # Build application
      - name: Compile Application
        run: go build -v ./...
        working-directory: ./

      # Run tests
      - name: Run Tests
        run: go test -v ./...
        working-directory: ./
