name: OpenAPI Builder

# Todo: Make this only for merges on main
on:
  pull_request:
    paths:
      - ".vscode/**"

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'placeholder-app' }}
    steps:
      - name: Generate OpenAPI Docs
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: html2
          openapi-file: .vscode/openapi.yml
          command-args: --skip-validate-spec -o ./documentation

      - name: Push to Documentation Repo
        uses: actions/checkout@v3
        with:
          name: placeholder-app/api-docs
          ref: refs/heads/master
          token: ${{ secrets.API_TOKEN }}
        run: |
          cd ./documentation
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[bot] Documentation Update"
          git push origin --force
